[package]
name = "npm-tools"
version = "0.1.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]

[dependencies]
serde_json = "0.7.4"
serde = "0.7.14"
quick-error = "1.1.0"

[dev-dependencies]
hamcrest = "*"
tempdir = "^0.3"
fs-utils = "*"
